language: generic

git:
  depth: 10
  submodules: false

env:
  global:
   - CCACHE_TEMPDIR=/tmp/.ccache-temp
   - CCACHE_COMPRESS=1
   - HEAVY_JOBS="2"
   - PREFIX=/tmp/mapnik
   - secure: "N3a5nzzsgpuu45k8qWdYsHNxrSnqeAGLTOYpfYoAH7B94vuf7pa7XV1tQjXbxrnx2D6ryTdtUtyRKwy7zXbwXxGt4DpczWEo8f6DUd6+obAp3kdnXABg2Sj4oA7KMs0F0CmoADy0jdUZD5YyOJHu64LCIIgzEQ9q49PFMNbU3IE="
   - secure: "iQYPNpMtejcgYeUkWZGIWz1msIco5qydJrhZTSCQOYahAQerdT7q5WZEpEo3G6IWOGgO1eo7GFuY8DvqQjw1+jC9b9mhkRNdo3LhGTKS9Gsbl5Q27k0rjlaFZmmQHrfPlQJwhfAIp+KLugHtQw5bCoLh+95E3j0F0DayF1tuJ3s="
   - secure: "F6ivqDNMBQQnrDGA9+7IX+GDswuIqQQd7YPJdQqa2Ked9jddAQDeJClb05ig3JlwfOlYLGZOd43ZX0pKuMtI2Gbkwz211agGP9S3YunwlRg8iWtJlO5kYFUdKCmJNhjg4icfkGELCgwXn+zuEWFSLpkPcjqAFKFlQrIJeAJJgKM="
addons:
  postgresql: "9.4"

cache:
  directories:
  - $HOME/.ccache

matrix:
  include:
    - os: linux
      sudo: false
      compiler: ": clang"
      env: JOBS=8 MASON_PUBLISH=true CXX="ccache clang++-3.8 -Qunused-arguments" CC="clang-3.8" TRIGGER=true
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'libstdc++-5-dev', 'xutils-dev']
    - os: linux
      sudo: false
      compiler: ": clang-coverage"
      env: JOBS=8 COVERAGE=true CXX="ccache clang++-3.8 -Qunused-arguments" CC="clang-3.8"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: ['libstdc++-5-dev', 'xutils-dev' ]
    - os: osx
      compiler: ": clang-osx"
      # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
      osx_image: xcode7.3 # upgrades clang from 6 -> 7
      env: JOBS=4 MASON_PUBLISH=true CXX="ccache clang++ -Qunused-arguments"

before_install:
 # workaround travis rvm bug
 # http://superuser.com/questions/1044130/why-am-i-having-how-can-i-fix-this-error-shell-session-update-command-not-f
 - |
   if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
     rvm get head || true
   fi
 - source scripts/travis-common.sh
 - export PYTHONUSERBASE=$(pwd)/mason_packages/.link
 - export PATH=${PREFIX}/bin:$(pwd)/mason_packages/.link/bin:${PYTHONUSERBASE}/bin:${PATH}
 - export COVERAGE=${COVERAGE:-false}
 - export MASON_PUBLISH=${MASON_PUBLISH:-false}
 - export BENCH=${BENCH:-false}
 - if [[ ${TRAVIS_BRANCH} != 'master' ]]; then export MASON_PUBLISH=false; fi
 - if [[ ${TRAVIS_PULL_REQUEST} != 'false' ]]; then export MASON_PUBLISH=false; fi
 - git_submodule_update --init --depth=10

install:
 - on 'linux' export PYTHONPATH=${PYTHONUSERBASE}/lib/python2.7/site-packages
 - on 'osx' export PYTHONPATH=${PYTHONUSERBASE}/lib/python/site-packages
 - on 'osx' export DATA_PATH=$(brew --prefix)/var/postgres
 - on 'osx' rm -rf ${DATA_PATH}
 - on 'osx' initdb ${DATA_PATH} -E utf8
 - on 'osx' pg_ctl -w start -l postgres.log --pgdata ${DATA_PATH};
 - on 'osx' cat postgres.log;
 - on 'osx' createuser -s postgres
 - psql -c 'create database template_postgis;' -U postgres
 - psql -c 'create extension postgis;' -d template_postgis -U postgres
 - enabled ${COVERAGE} pip install --user cpp-coveralls

before_script:
 - source bootstrap.sh
 - |
   if [[ $(uname -s) == 'Linux' ]]; then
     mason install clang 3.8.0
     export PATH=$(mason prefix clang 3.8.0)/bin:${PATH}
     which clang++
     export LLVM_COV="$(mason prefix clang 3.8.0)/bin/llvm-cov"
   fi
 - ccache --version
 - ccache -p || true
 - ccache --show-stats || true
 - commit_message_parse

script:
 - export SCONSFLAGS='--debug=time'
 - configure BENCHMARK=${BENCH}
 - cat config.log
 # we limit the `make` to 40 min
 # to ensure that slow builds still upload their
 # ccache results and therefore should be faster
 # (and might work) for the next build
 - DURATION=2400
 - scripts/travis-command-wrapper.py -s "date" -i 120 --deadline=$(( $(date +%s) + ${DURATION} )) make
 - make test
 - enabled ${COVERAGE} coverage
 - enabled ${BENCH} make bench

after_success:
 - enabled ${TRIGGER} trigger_downstream
 - if enabled ${MASON_PUBLISH}; then
     source ./.mason/mason.sh &&
     ./mason_latest.sh build &&
     ./mason_latest.sh publish;
   fi
